[package]
name = "git_ignore"
version = "0.1.1"
authors = ["Nathan Kleyn <nathan@nathankleyn.com>"]
description = "Implementation of .gitignore file parsing and glob testing in Rust."
license = "MIT"
repository = "https://github.com/nathankleyn/git_ignore.rs"

[dependencies]
glob = "0.2.10"
tempdir = "0.3.0"
